### ISSUE TITLE
Bug Report: Touble to download a complete series that have more than one season

### ISSUE THREAD

**Issue by KywoSkylake** [ByteDream/crunchyroll-go#16] opened 2022-02-14 14:37 UTC
Hi,

First of all, thank you for your hard work, the downloader is amazing.

But I found a strange bug, I noticed it now on several series.

For Example I tried to download The Fruit of Grisaia. 
I entered fallowing command to download the series.
```
crunchy download -r best --output "{series_name} - S{season_number}E{episode_number} - {title}.mkv" --audio ja-JP --subtitle de-DE --no-hardsub https://www.crunchyroll.com/the-fruit-of-grisaia
```
But somehow it randomly takes some Episodes from Season 1 and then from Season 3:
```
=> ✔ Logged in 
=> ✔ Parsed url 1 with 14 successes and 0 fails
=> 14 of 14 episodes could be parsed

=> Downloads:
=> 	1. Ordinary Academy Life » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E01)
=> 	2. School Killer Sakaki » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E02)
=> 	3. The Cocoon of Caprice III » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S03E03)
=> 	4. Where to Aim the Silver Bullet » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E04)
=> 	5. The Seed of Blanc Aile I » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S03E05)
=> 	6. The Seed of Blanc Aile II » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S03E06)
=> 	7. The Seed of Blanc Aile III » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S03E07)
=> 	8. Seed of the World Tree I » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E08)
=> 	9. Seed of the World Tree II » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E09)
=> 	10. Angelic Howl I » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E10)
=> 	11. Angelic Howl II » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E11)
=> 	12. Angelic Howl III » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E12)
=> 	13. 10 Centimeter Field of Fire » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E13)
=> 	14. The Cocoon of Caprice 0 » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S02E14)
```

As you saw, episode 1 - 2 are from season 1 and episode 3 is randomly from season 3

I noticed the bug also on

- My Teen Romantic Comedy SNAFU
- Is It Wrong to Try to Pick Up Girls in a Dungeon?
- My Next Life as a Villainess

In my opinion this problem only occurs on shows that have more than one seasons.

I tried then to download them link by link using fallowing command

I used `lynx -dump https://www.crunchyroll.com/the-fruit-of-grisaia | awk '/http/{print $2}' | grep -Ei episode` to get a list of episodes

```
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-10-the-seed-of-blanc-aile-vi-678079
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-9-the-seed-of-blanc-aile-v-678077
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-8-the-seed-of-blanc-aile-iv-678075
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-7-the-seed-of-blanc-aile-iii-678073
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-6-the-seed-of-blanc-aile-ii-678071
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-5-the-seed-of-blanc-aile-i-678069
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-4-the-cocoon-of-caprice-iv-678067
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-3-the-cocoon-of-caprice-iii-678065
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-2-the-cocoon-of-caprice-ii-678063
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-1-the-cocoon-of-caprice-i-678061
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-14-the-cocoon-of-caprice-0-678007
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-13-10-centimeter-field-of-fire-661517
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-12-angelic-howl-iii-661515
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-11-angelic-howl-ii-661513
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-10-angelic-howl-i-661511
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-9-seed-of-the-world-tree-ii-661509
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-8-seed-of-the-world-tree-i-661507
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-7-letter-of-happiness-661505
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-6-raison-dtre-661503
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-5-vox-in-box-661501
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-4-where-to-aim-the-silver-bullet-661499
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-3-sweet-diet-661497
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-2-school-killer-sakaki-661495
https://www.crunchyroll.com/the-fruit-of-grisaia/episode-1-ordinary-academy-life-661493
```

Then I run the command to download every episode link by link

```
lynx -dump https://www.crunchyroll.com/the-fruit-of-grisaia | awk '/http/{print $2}' | grep -Ei episode | parallel -j 1 '~/Tools/crunchyroll-go/crunchy download -r best --output "{series_name} - S{season_number}E{episode_number} - {title}.mkv" --audio ja-JP --subtitle de-DE --no-hardsub {}'
```
After the Download has finished, I noticed that some files had the same file name, for example S01E02 exists twice
```
./The Fruit of Grisaia - S01E02 - School Killer Sakaki (0).mkv
./The Fruit of Grisaia - S01E13 - 10 Centimeter Field of Fire.mkv
./The Fruit of Grisaia - S01E10 - Angelic Howl I.mkv
./The Fruit of Grisaia - S01E04 - Where to Aim the Silver Bullet.mkv
./The Fruit of Grisaia - S01E04 - Where to Aim the Silver Bullet (0).mkv
./The Fruit of Grisaia - S02E14 - The Cocoon of Caprice 0.mkv
./The Fruit of Grisaia - S01E08 - Seed of the World Tree I.mkv
./The Fruit of Grisaia - S01E07 - Letter of Happiness (0).mkv
./The Fruit of Grisaia - S01E07 - Letter of Happiness.mkv
./The Fruit of Grisaia - S03E01 - The Cocoon of Caprice I.mkv
./The Fruit of Grisaia - S01E02 - School Killer Sakaki.mkv
./The Fruit of Grisaia - S03E09 - The Seed of Blanc Aile V.mkv
./The Fruit of Grisaia - S03E03 - The Cocoon of Caprice III.mkv
./The Fruit of Grisaia - S01E11 - Angelic Howl II.mkv
./The Fruit of Grisaia - S03E06 - The Seed of Blanc Aile II.mkv
./The Fruit of Grisaia - S03E05 - The Seed of Blanc Aile I.mkv
./The Fruit of Grisaia - S01E10 - Angelic Howl I (0).mkv
./The Fruit of Grisaia - S03E01 - The Cocoon of Caprice I (0).mkv
./The Fruit of Grisaia - S03E05 - The Seed of Blanc Aile I (0).mkv
./The Fruit of Grisaia - S01E09 - Seed of the World Tree II.mkv
./The Fruit of Grisaia - S01E08 - Seed of the World Tree I (0).mkv
./The Fruit of Grisaia - S01E12 - Angelic Howl III.mkv
./The Fruit of Grisaia - S01E06 - Raison D'être.mkv
./The Fruit of Grisaia - S03E03 - The Cocoon of Caprice III (0).mkv
```
I checked the md5sum of these two, and both were different
```
948d23a154a245f33f1ef5123831a53a  The Fruit of Grisaia - S01E02 - School Killer Sakaki.mkv
b2a6bca9f9f8c09f2e7cdbd2acdb633a  The Fruit of Grisaia - S01E02 - School Killer Sakaki (0).mkv
```
But the video content is the same, so it downloaded the episode twice.

And that's strange, I cannot explain why this happens do you have an idea?

Thank you in advance
Mike

**Comment by ByteDream** [comment] 2022-02-14 16:37
Yes I can confirm this error, very interesting xD
```
=> Downloads:
=>      1. Ordinary Academy Life » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E01)
=>      2. School Killer Sakaki » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E02)
=>      3. Sweet Diet » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E03)
=>      4. The Cocoon of Caprice IV » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S03E04)
=>      5. VOX IN BOX » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E05)
=>      6. The Seed of Blanc Aile II » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S03E06)
=>      7. The Seed of Blanc Aile III » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S03E07)
=>      8. Seed of the World Tree I » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E08)
=>      9. The Seed of Blanc Aile V » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S03E09)
=>      10. The Seed of Blanc Aile VI » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S03E10)
=>      11. Angelic Howl II » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E11)
=>      12. Angelic Howl III » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E12)
=>      13. 10 Centimeter Field of Fire » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S01E13)
=>      14. The Cocoon of Caprice 0 » 1920x1080px, 23.97 FPS, Japanese audio (The Fruit of Grisaia S02E14)
```
I think this is caused because the episodes are sorted after their episode number but not separate by seasons before (this also explains why my output differs from yours). 

I'm currently working on the next version ([v2](https://github.com/ByteDream/crunchyroll-go/tree/v2)) of this project, so no major changes will be made to the current version anymore and the solution of this problem would be such a major change.
But I'm looking forward to release the next version in the next few days, the error is also fixed there:
```
➞ The Fruit of Grisaia Season 1
➞       1. Leben als normaler Schüler » 1920x1080px, 23.97 FPS (S01E01)
➞       2. School Killer Yumiko » 1920x1080px, 23.97 FPS (S01E02)
➞       3. Süße Ernährung » 1920x1080px, 23.97 FPS (S01E03)
➞       4. Das Ziel für die Silberkugel » 1920x1080px, 23.97 FPS (S01E04)
➞       5. VOX IN BOX » 1920x1080px, 23.97 FPS (S01E05)
➞       6. Raison d’être » 1920x1080px, 23.97 FPS (S01E06)
➞       7. Brief der Glücklichkeit » 1920x1080px, 23.97 FPS (S01E07)
➞       8. Die Saat des Weltenbaums – Teil 1 » 1920x1080px, 23.97 FPS (S01E08)
➞       9. Die Saat des Weltenbaums – Teil 2 » 1920x1080px, 23.97 FPS (S01E09)
➞       10. Angelic Howl – Teil 1 » 1920x1080px, 23.97 FPS (S01E10)
➞       11. Angelic Howl – Teil 2 » 1920x1080px, 23.97 FPS (S01E11)
➞       12. Angelic Howl – Teil 3 » 1920x1080px, 23.97 FPS (S01E12)
➞       13. 10 Zentimeter Schussfeld » 1920x1080px, 23.97 FPS (S01E13)
➞ The Fruit of Grisaia Season 2
➞       1. Der Kokon der Caprice, Teil 0 » 1920x1080px, 23.97 FPS (S02E14)
➞ The Fruit of Grisaia Season 3
➞       1. Der Kokon der Caprice – Teil 1 » 1920x1080px, 23.97 FPS (S03E01)
➞       2. Der Kokon der Caprice – Teil 2 » 1920x1080px, 23.97 FPS (S03E02)
➞       3. Der Kokon der Caprice – Teil 3 » 1920x1080px, 23.97 FPS (S03E03)
➞       4. Der Kokon der Caprice – Teil 4 » 1920x1080px, 23.97 FPS (S03E04)
➞       5. Die Saat des Blanc Aile – Teil 1 » 1920x1080px, 23.97 FPS (S03E05)
➞       6. Die Saat des Blanc Aile – Teil 2 » 1920x1080px, 23.97 FPS (S03E06)
➞       7. Die Saat des Blanc Aile – Teil 3 » 1920x1080px, 23.97 FPS (S03E07)
➞       8. Die Saat des Blanc Aile – Teil 4 » 1920x1080px, 23.97 FPS (S03E08)
➞       9. Die Saat des Blanc Aile – Teil 5 » 1920x1080px, 23.97 FPS (S03E09)
➞       10. Die Saat des Blanc Aile – Teil 6 » 1920x1080px, 23.97 FPS (S03E10)
```
(The v2 branch cannot be compiled currently)

**Comment by KywoSkylake** [comment] 2022-02-14 17:33
No problem, take your time xD

I'm looking forward to it.

Thanks

**Comment by ByteDream** [comment] 2022-03-22 19:10
> But I'm looking forward to release the next version in the next few days

Haha well, but now fixed in version [v2](https://github.com/ByteDream/crunchyroll-go/releases/tag/v2.0.0).

**Closed by ByteDream** 2022-03-22 19:10 UTC
Labels: bug, cli
