### ISSUE TITLE
login failed with go runtime error

### ISSUE THREAD

**Issue by hekmon** [ByteDream/crunchyroll-go#27] opened 2022-05-01 08:53 UTC
```
[debug] Executing `login` command with 2 arg(s)
[debug] Logging in via credentials
[err] interface conversion: interface {} is nil, not map[string]interface {}: goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.18.1/libexec/src/runtime/debug/stack.go:24 +0x68
github.com/ByteDream/crunchyroll-go/cmd/crunchyroll-go/cmd.Execute.func1()
```

By poking around in the code, I found out that login queries where denied (most likely by cloudflare) with `429 Too Many Requests` and returned body was empty, preventing the casting of non present values.

I will send you a PR handling such cases.

**Comment by ByteDream** [comment] 2022-05-01 10:14
Thanks for investigating and hunting down the error!
It was already reported in #14 before but I closed it since the author didn't respond to my further questions and I could not reproduce it, so I thought the error were only temporary / with the last comment in mind, a VPN or proxy error.

**Comment by ByteDream** [comment] 2022-05-01 10:29
Did you use your "normal" internet connection or some kind of vpn or proxy?

**Comment by hekmon** [comment] 2022-05-01 11:42
Yes, 100% vanilla direct connection. Actually I think the rate limiting occurred before that:

- the last ep of season download batch failed: the error told me that I was not logged in
- tried to login: failed with runtime error

You know the rest of the story :) I suspect the rate limiting was the reason of the ep failure but maybe the downloader code part interpreted the fails as a not logged in situation... At least with the PR, user will try to login again and he will have the actual HTTP code (for logging in). I think the same enhancement of error handling could be done on the downloader part too. At least now, no more runtime panic !

**Closed** 2022-05-01 12:12 UTC
Labels: bug, cli, library
