### ISSUE TITLE
Incorrectly encapsulating multiple video streams as well as audio streams

### ISSUE THREAD

**Issue by ltsj** [ByteDream/crunchyroll-go#36] opened 2022-06-04 12:52 UTC
When I download https://beta.crunchyroll.com/watch/GJWU2XQDD/sound-hashira-tengen-uzui, it has two S2 one is "Demon Slayer: Mugen Train Arc" and the other is "Demon Slayer: Entertainment District Arc" "
When I set the parameter to S2E1 it downloads the first episode of "Demon Slayer: Mugen Train Arc" and the first episode of "Demon Slayer: Entertainment District Arc" and packages them together, but it's actually two different seasons.

Same with this, when I download S1E7 of https://beta.crunchyroll.com/series/GNVHKN7M4/shikimoris-not-just-a-cutie, it turns the previous episode "S1 E-SP - Special" Encapsulating them together will result in a mkv file containing two video streams and audio streams, which is the same as the above

**Comment by ByteDream** [comment] 2022-06-07 17:01
*Argh once again crunchyroll upfucks.*

> When I download https://beta.crunchyroll.com/watch/GJWU2XQDD/sound-hashira-tengen-uzui, it has two S2 one is "Demon Slayer: Mugen Train Arc" and the other is "Demon Slayer: Entertainment District Arc" "
When I set the parameter to S2E1 it downloads the first episode of "Demon Slayer: Mugen Train Arc" and the first episode of "Demon Slayer: Entertainment District Arc" and packages them together, but it's actually two different seasons.

Upfuck 1: The Mugen Train Arc and Entertainment District Arc are both flagged as season 2 but separated in different seasons. As you can see both have the `S2` prefix:
![image](https://user-images.githubusercontent.com/63594396/172438038-3b93cc16-79c5-421c-ab89-bd74ea0dbe43.png)
Just see it like this: "It's not a bug, it's a feature". Only this mindset can help you if you dive deeper in the crunchyroll api.

> Same with this, when I download S1E7 of https://beta.crunchyroll.com/series/GNVHKN7M4/shikimoris-not-just-a-cutie, it turns the previous episode "S1 E-SP - Special" Encapsulating them together will result in a mkv file containing two video streams and audio streams, which is the same as the above

Upfuck 2: There is a special between normal episodes which is also flagged as episode 7, just like the actual 7th episode. Why do you ask? I have no f... idea, only god and crunchy knows :))). TLDR; I cannot do much about it, there is no way how I can filter the special episodes out. I _could_ add a check if the title is `SP` or contains `special` but this creates more issues than it solves.

---

To say it clearly: **I can't do anything about it.**
This time the errors are clearly on crunchyrolls side and sadly I do not have the required contacts to change this. I'll leave this issue open, maybe there will be a fix for this somewhere in the future.
Crunchyroll at its best.

**Comment by ltsj** [comment] 2022-06-07 17:36
thanks for your answer😀

**Closed** 2022-06-27 12:08 UTC
Labels: bug, cli, wtf is wrong with you crunchyroll
