### ISSUE TITLE
Login failure - invalid session id, user is not logged in

### ISSUE THREAD

**Issue by kuusei** [ByteDream/crunchyroll-go#30] opened 2022-05-10 02:56 UTC
Hi, When I try to log in using crunchy, I get the following message from below and need to wait a while or switch proxies to use it
`crunchy login --persistent <email> <password> -p http://127.0.0.1:****`
`invalid session id, user is not logged in`

os: windows 11 22000
version: 2.2.1 (Installation via scoop)

**Comment by ByteDream** [comment] 2022-05-10 06:16
Does it work if you switch to another proxy or using none at all?

**Comment by kuusei** [comment] 2022-05-10 11:45
Switch the proxy and wait for a period of time, or wait for a period of time without switching the proxy is also effective

Not available in my country without proxy crunchyroll

**Comment by ByteDream** [comment] 2022-05-16 16:24
I've managed to reproduce it now. When logging in, the crunchy server should always return the same response when the correct credentials are given, but in some cases it doesn't. And I have absolutely no idea why because it makes no really sense. It may be a rate limit or something but they return nothing which could point to this. Some internal calls use and expect the data that is missing from the login request, and therefore your error is (incorrectly) raised.
A fix for will be available in the next few days, until then you have to continue switching your proxies.

**Comment by ByteDream** [comment] 2022-05-16 17:15
![image](https://user-images.githubusercontent.com/63594396/168647154-0ab11ffd-fe26-497e-8adb-3dca8bf5a7d4.png)
Well ok my initial thought how to fix it won't work. When requesting login multiple time, this error eventually happens (translated: "A system error occurred. Please contact us for help")

**Comment by Askadelion** [comment] 2022-05-17 06:33
> ![image](https://user-images.githubusercontent.com/63594396/168647154-0ab11ffd-fe26-497e-8adb-3dca8bf5a7d4.png) Well ok my initial thought how to fix it won't work. When requesting login multiple time, this error eventually happens (translated: "A system error occurred. Please contact us for help")

Das liegt daran das du den Login nicht offen hälst durch cookies oder sieht zumindest für mich danach aus, die zeitlichen abstände sind zu Kurz nach dem login bei jeden Download Loggt er sich erneut ein mich wirft er beim 4. Mal raus.
Wenn ich aber etwas warte ca 5 bis 10 minuten bis zum nächsten download kommt dieser Fehler nicht.
(war jetzt zufaul es zu übersetzen)

**Comment by ByteDream** [comment] 2022-05-18 08:58
After some research I've came to the same conclusion. This is fixed in afa975c459947f613ea950ae2927d596918530ca which caches the session id in a temporary file.

**Comment by ByteDream** [comment] 2022-05-18 09:21
Fixed in [v2.2.2](https://github.com/ByteDream/crunchyroll-go/releases/tag/v2.2.2).

**Closed by ByteDream** 2022-05-18 09:21 UTC
Labels: bug, cli, library

**Comment by DxsSucuk** [comment] 2022-05-19 14:10
Wouldn't it be better to store the SessionID only for the current CLI Session, or check if there is a login failure after a automatic login, and if so the SessionID should be deleted + creds should be entered again by the user.

**Comment by ByteDream** [comment] 2022-05-19 14:37
This is how the session id is stored / login process is structured if logged in persistent with credentials.

```mermaid
graph TD;
    A["Does session id exist (stored in a temporary file, e.g. /tmp/.crunchy on linux)"];
    A -- Yes --> B[Does logging in with the id work];
    A -- No --> C["Login with credentials (which are stored on a peristent location) and store the session id in the temporary file"];
    B -- Yes --> D[Download requested episode etc.];
    B -- No --> C;
    C --> D;
```

**Comment by DxsSucuk** [comment] 2022-05-20 07:06
Instead of storing the Creds in clear text, wouldn't it be better to encrypt it with a specific password that the user has to enter upon cred load?

**Comment by ByteDream** [comment] 2022-05-20 07:56
This is a good idea for [v3](https://github.com/users/ByteDream/projects/1/views/1)
